server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://115.29.196.128:3306/yuoa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: yuoa
    password: 82fhPK2x8YniJzzJ
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huifeit.yuoa.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
